### ISSUE TITLE
Multiple recipes have download URLs pointing to specific versions

### ISSUE THREAD

**Issue by homebysix** [autopkg/paul-cossey-recipes#3]
I've noticed that a few of your download recipes have URLDownloader download URLs pointing to specific version downloads. This defeats the purpose of AutoPkg, as it will never obtain a newer version from the vendor.

Examples include:

- [Causality.download](https://github.com/autopkg/paul-cossey-recipes/blob/be45ac4f61be8dc6cb90bc8f47633ed8b25ca3b8/Causality/Causality.download.recipe#L26)
- [MURAL.download](https://github.com/autopkg/paul-cossey-recipes/blob/be45ac4f61be8dc6cb90bc8f47633ed8b25ca3b8/MURAL/MURAL.download.recipe#L26)
- [Pd.download](https://github.com/autopkg/paul-cossey-recipes/blob/be45ac4f61be8dc6cb90bc8f47633ed8b25ca3b8/Pd/Pd.download.recipe#L28)
- [Scenarist.download](https://github.com/autopkg/paul-cossey-recipes/blob/be45ac4f61be8dc6cb90bc8f47633ed8b25ca3b8/Scenarist/Scenarist.download.recipe#L26)

It appears you created these recipes using Recipe Robot, which in most cases should have warned you of this condition at runtime:

```
Processing: https://download.mural.co/mac-app/MURAL-1.0.11.dmg
Input path looks like a download URL.
    Download URL is: https://download.mural.co/mac-app/MURAL-1.0.11.dmg
[WARNING] Careful, this might be a version-specific URL. Better to give me a "latest" URL or a Sparkle feed.
```

Additionally the [set.a.light%203D.V2.5.download](https://github.com/autopkg/paul-cossey-recipes/blob/be45ac4f61be8dc6cb90bc8f47633ed8b25ca3b8/elixxier%20Software%20GmbH/set.a.light%203D.V2.5.download.recipe#L8) recipe appears to download a newer version, but the filename, description, and name used in the recipe says `2.5`. The recipe also includes a version in the identifier, which is not advisable.

Could you take a look at these recipes and add [URLTextSearcher](https://github.com/autopkg/autopkg/wiki/Processor-URLTextSearcher) or another URL provider as needed to make the above recipes non-version-specific? Thank you!

**Comment by paul-cossey** [comment]
Thanks, @homebysix 

I'd been meaning to audit these for a while, just never got round to it. They _should_ all be fixed now. 

Yeah, I know version numbers in the names/identifier aren't ideal, but in this case v2.5 is in the `CFBundleName` and `CFBundleDisplayName`. I'm no longer working at the place I created these for, so will leave the names as they are for now, but this has nudged me to create an installs array for it :-) 

```
<key>CFBundleName</key>
<string>SAL V2.5</string>
<key>CFBundleDisplayName</key>
<string>set.a.light 3D v2.5</string>
```

Thanks
Paul
