### ISSUE TITLE
PureData download link appears to be bad

### ISSUE THREAD

**Issue by kclose3** [autopkg/paul-cossey-recipes#6]
Looking at the PureData download recipe, it looks like the new download link has changed to https://msp.ucsd.edu/Software/pd-0.54-1.macos.zip

**Comment by paul-cossey** [comment]
Sorry for the delay, @kclose3 (This isn't a recipe I use any more.) 

I've updated the regex, can you give this a try for me please? https://github.com/autopkg/paul-cossey-recipes/commit/790c4cc998e6eb715e8ab55a041c159eb6c17d1a

**Comment by kclose3** [comment]
Sorry, we ended up just creating our own recipe (based on yours) that works. 

For reference, our RegEx is:

`<key>re_pattern</key>`
`<string>href=\"(https://msp\.ucsd\.edu/Software/pd-\d\.\d\d-\d\.macos\.zip)\"</string>`

**Comment by paul-cossey** [comment]
Is your recipe public? If so I could depreciate mine and point folks to yours?

**Comment by kclose3** [comment]
Unfortunately, ours is internal only.

**Comment by paul-cossey** [comment]
Ok, fair enough. I'm confident my changes to this work so I'll close this off. Thanks for raising
